spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lost_and_found
    username: root
    password: abc123
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: spring-ai-demo
  ai:
    zhipuai:
      api-key: 735122b7d0391a7ecf8554ee43cdf62a.uNn7AbRulHHOiSn3
      chat:
        options:
          model: glm-4-air
          temperature: 0.7
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\\img\\
---
server:
  port: 8081
logging:
  level:
    root: warn
spring:
  config:
    activate:
      on-profile: dev
---
server:
  port: 8090
logging:
  level:
    root: warn
    org.mybatis: warn # 将MyBatis日志级别设置为warn
    org.apache.ibatis: warn # 将Apache MyBatis日志级别设置为warn
    org.springframework: warn # 将Spring框架日志级别设置为warn
spring:
  config:
    activate:
      on-profile: test
---
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: pro
---
audioUrlPrefix: http://music.163.com/song/media/outer/url?id=