spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.149.136.157:3306/lost_and_found
    username: root
    password: abc123@ZBH
    type: com.alibaba.druid.pool.DruidDataSource
  transaction:
    default-timeout: 30
  application:
    name: spring-ai-demo
  ai:
    zhipuai:
      api-key: 735122b7d0391a7ecf8554ee43cdf62a.uNn7AbRulHHOiSn3
      chat:
        options:
          model: glm-4-air
          temperature: 0.7
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\\img\\
---
server:
  port: 8081
logging:
  level:
    root: warn
spring:
  config:
    activate:
      on-profile: dev
---
server:
  port: 8090
logging:
  level:
    root: warn
    org.mybatis: warn # 将MyBatis日志级别设置为warn
    org.apache.ibatis: warn # 将Apache MyBatis日志级别设置为warn
    org.springframework: warn # 将Spring框架日志级别设置为warn
spring:
  config:
    activate:
      on-profile: test
---
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: pro
---
server:
  servlet:
    session:
      timeout: PT60M # 设置session超时时间为60分钟

---
# 发送邮件的相关配置
spring:
  mail:
    host: smtp.qq.com # 邮箱服务器地址
    port: 465 # 邮箱服务器端口
    username: 1489526569@qq.com
    password: awlhzstdyhjsgggf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory # SSL连接配置
        debug: true
---

project:
  folder: d:/webser/myapps/lost_and_found/ # 项目目录

log:
  root:
    level: debug # 日志级别

